extends:
  "eslint:recommended"

parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    impliedStrict: true

env:
  node: true
  mongo: true

rules:
  curly: "error"
  eqeqeq: "error"